version: '3'

services:
  stac:
    container_name: stac-fastapi-pgstac
    image: stac-utils/stac-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - HOST=0.0.0.0
      - PORT=8082
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - MODULE_NAME=stac_fastapi.pgstac.app
      - VARIABLE_NAME=app
    ports:
      - "8082:8082"
    depends_on:
      - database

  titiler:
    container_name: titiler-pgstac
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2

      - PYTHONWARNINGS=ignore
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - WEB_CONCURRENCY=2
      - WORKERS_PER_CORE=1
      - MOSAIC_CONCURRENCY=1
    depends_on:
      - database

  database:
    container_name: stac-db
    build:
      context: .
      dockerfile: Dockerfile.pgstac
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

networks:
  default:
    name: stac-fastapi-network
